name: first workflow
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            -   name: echo a string 
                run: echo "hellow"
            -   name: Multiline command
                run: |
                    node -v
                    npm -v                    